package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name="etudiant"
    ,catalog="gestion_note_emsi"
)

public class Etudiant  implements java.io.Serializable {
    
     private int idE;
     private Groupe groupe;
     private String nom;
     private String prenom;
     private Set<Notes> noteses = new HashSet<Notes>(0);

    public Etudiant() {
    }

	
    public Etudiant(int idE, Groupe groupe, String nom, String prenom) {
        this.idE = idE;
        this.groupe = groupe;
        this.nom = nom;
        this.prenom = prenom;
    }
    public Etudiant(int idE, Groupe groupe, String nom, String prenom, Set<Notes> noteses) {
       this.idE = idE;
       this.groupe = groupe;
       this.nom = nom;
       this.prenom = prenom;
       this.noteses = noteses;
    }
   
     @Id 

    
    @Column(name="id_e", unique=true, nullable=false)
    public int getIdE() {
        return this.idE;
    }
    
    public void setIdE(int idE) {
        this.idE = idE;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_g", nullable=false)
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }

    
    @Column(name="nom", nullable=false, length=25)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", nullable=false, length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="etudiant")
    public Set<Notes> getNoteses() {
        return this.noteses;
    }
    
    public void setNoteses(Set<Notes> noteses) {
        this.noteses = noteses;
    }




}


