package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examen generated by hbm2java
 */
@Entity
@Table(name="examen"
    ,catalog="gestion_note_emsi"
)
public class Examen  implements java.io.Serializable {


     private int idEx;
     private Groupe groupe;
     private Module module;
     private Professeur professeur;
     private Date dateExamen;
     private Set<Notes> noteses = new HashSet<Notes>(0);

    public Examen() {
    }

	
    public Examen(int idEx, Groupe groupe, Module module, Professeur professeur, Date dateExamen) {
        this.idEx = idEx;
        this.groupe = groupe;
        this.module = module;
        this.professeur = professeur;
        this.dateExamen = dateExamen;
    }
    public Examen(int idEx, Groupe groupe, Module module, Professeur professeur, Date dateExamen, Set<Notes> noteses) {
       this.idEx = idEx;
       this.groupe = groupe;
       this.module = module;
       this.professeur = professeur;
       this.dateExamen = dateExamen;
       this.noteses = noteses;
    }
   
     @Id 

    
    @Column(name="id_ex", unique=true, nullable=false)
    public int getIdEx() {
        return this.idEx;
    }
    
    public void setIdEx(int idEx) {
        this.idEx = idEx;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_g", nullable=false)
    public Groupe getGroupe() {
        return this.groupe;
    }
    
    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_M", nullable=false)
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_p", nullable=false)
    public Professeur getProfesseur() {
        return this.professeur;
    }
    
    public void setProfesseur(Professeur professeur) {
        this.professeur = professeur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateExamen", nullable=false, length=10)
    public Date getDateExamen() {
        return this.dateExamen;
    }
    
    public void setDateExamen(Date dateExamen) {
        this.dateExamen = dateExamen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="examen")
    public Set<Notes> getNoteses() {
        return this.noteses;
    }
    
    public void setNoteses(Set<Notes> noteses) {
        this.noteses = noteses;
    }

    @Override
    public String toString() {
        return "CC :"  + idEx + " - " + module +" - "+dateExamen ;
    }




}


