package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="groupe"
    ,catalog="gestion_note_emsi"
)
public class Groupe  implements java.io.Serializable {


     private int idG;
     private String libele;
     private List<Etudiant> etudiants = new ArrayList<Etudiant>(0);
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Groupe() {
    }

	
    public Groupe(int idG, String libele) {
        this.idG = idG;
        this.libele = libele;
    }
    public Groupe(int idG, String libele, List<Etudiant> etudiants, Set<Examen> examens) {
       this.idG = idG;
       this.libele = libele;
       this.etudiants = etudiants;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="id_g", unique=true, nullable=false)
    public int getIdG() {
        return this.idG;
    }
    
    public void setIdG(int idG) {
        this.idG = idG;
    }

    
    @Column(name="libele", nullable=false, length=25)
    public String getLibele() {
        return this.libele;
    }
    
    public void setLibele(String libele) {
        this.libele = libele;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public List<Etudiant> getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(List<Etudiant> etudiants) {
        this.etudiants = etudiants;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="groupe")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

    @Override
    public String toString() {
        return  libele ;
    }




}


