package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name="notes"
    ,catalog="gestion_note_emsi"
)
public class Notes  implements java.io.Serializable {


     private NotesId id;
     private Etudiant etudiant;
     private Examen examen;
     private BigDecimal note;

    public Notes() {
    }

    public Notes(NotesId id, Etudiant etudiant, Examen examen, BigDecimal note) {
       this.id = id;
       this.etudiant = etudiant;
       this.examen = examen;
       this.note = note;
    }
    public Notes(NotesId id, Etudiant etudiant, Examen examen) {
       this.id = id;
       this.etudiant = etudiant;
       this.examen = examen;
      
    }
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idEx", column=@Column(name="id_ex", nullable=false) ), 
        @AttributeOverride(name="idE", column=@Column(name="id_e", nullable=false) ) } )
    public NotesId getId() {
        return this.id;
    }
    
    public void setId(NotesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_e", nullable=false, insertable=false, updatable=false)
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ex", nullable=false, insertable=false, updatable=false)
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }

    
    @Column(name="note", nullable=false, precision=4)
    public BigDecimal getNote() {
        return this.note;
    }
    
    public void setNote(BigDecimal note) {
        this.note = note;
    }




}


