package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotesId generated by hbm2java
 */
@Embeddable
public class NotesId  implements java.io.Serializable {


     private int idEx;
     private int idE;

    public NotesId() {
    }

    public NotesId(int idEx, int idE) {
       this.idEx = idEx;
       this.idE = idE;
    }
   


    @Column(name="id_ex", nullable=false)
    public int getIdEx() {
        return this.idEx;
    }
    
    public void setIdEx(int idEx) {
        this.idEx = idEx;
    }


    @Column(name="id_e", nullable=false)
    public int getIdE() {
        return this.idE;
    }
    
    public void setIdE(int idE) {
        this.idE = idE;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotesId) ) return false;
		 NotesId castOther = ( NotesId ) other; 
         
		 return (this.getIdEx()==castOther.getIdEx())
 && (this.getIdE()==castOther.getIdE());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEx();
         result = 37 * result + this.getIdE();
         return result;
   }   


}


