package emsi.ma.gestion_note.models;
// Generated Jan 10, 2023 1:29:41 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professeur generated by hbm2java
 */
@Entity
@Table(name="professeur"
    ,catalog="gestion_note_emsi"
)
public class Professeur  implements java.io.Serializable {


     private int idP;
     private String nomProf;
     private String prenomProf;
     private String specialite;
     private Set<Examen> examens = new HashSet<Examen>(0);

    public Professeur() {
    }

	
    public Professeur(int idP, String nomProf, String prenomProf, String specialite) {
        this.idP = idP;
        this.nomProf = nomProf;
        this.prenomProf = prenomProf;
        this.specialite = specialite;
    }
    public Professeur(int idP, String nomProf, String prenomProf, String specialite, Set<Examen> examens) {
       this.idP = idP;
       this.nomProf = nomProf;
       this.prenomProf = prenomProf;
       this.specialite = specialite;
       this.examens = examens;
    }
   
     @Id 

    
    @Column(name="id_p", unique=true, nullable=false)
    public int getIdP() {
        return this.idP;
    }
    
    public void setIdP(int idP) {
        this.idP = idP;
    }

    
    @Column(name="nomProf", nullable=false, length=25)
    public String getNomProf() {
        return this.nomProf;
    }
    
    public void setNomProf(String nomProf) {
        this.nomProf = nomProf;
    }

    
    @Column(name="prenomProf", nullable=false, length=25)
    public String getPrenomProf() {
        return this.prenomProf;
    }
    
    public void setPrenomProf(String prenomProf) {
        this.prenomProf = prenomProf;
    }

    
    @Column(name="specialite", nullable=false, length=25)
    public String getSpecialite() {
        return this.specialite;
    }
    
    public void setSpecialite(String specialite) {
        this.specialite = specialite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professeur")
    public Set<Examen> getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set<Examen> examens) {
        this.examens = examens;
    }

    @Override
    public String toString() {
        return nomProf ;
    }

   


}


