/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emsi.ma.gestion_note.views;

import emsi.ma.gestion_note.dao.MyHibernateUtil;
import emsi.ma.gestion_note.models.Etudiant;
import emsi.ma.gestion_note.models.Examen;
import emsi.ma.gestion_note.models.Groupe;
import emsi.ma.gestion_note.models.Notes;
import emsi.ma.gestion_note.models.NotesId;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author zakaria
 */
public class JIFrameSaisirNotes extends javax.swing.JInternalFrame {
        Session s; 
        EcouteurExamen ec = new EcouteurExamen();
    /**
     * Creates new form JIFrameSaisirNotes
     */
    public JIFrameSaisirNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        comgroupe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comexam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Groupe :");

        comgroupe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comgroupeItemStateChanged(evt);
            }
        });

        jLabel2.setText("Examen :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDE", "Nom", "Prenom", "Note"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jScrollPane1.setViewportView(jScrollPane2);

        jButton1.setText("Enregister la saisie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comgroupe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comexam, 0, 211, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comgroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(comexam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:   load group
        s=MyHibernateUtil.getSession();
        List<Groupe> lg=s.createQuery("from Groupe").list();
        for(Groupe g: lg)
            comgroupe.addItem(g);
        
        comexam.addItemListener(ec);
    }//GEN-LAST:event_formInternalFrameOpened

    private void comgroupeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comgroupeItemStateChanged
        // TODO add your handling code here:   filter exam by group
        comexam.removeItemListener(ec);
        Query rqt= s.createQuery("from Examen ex where ex.groupe.idG =:id_g");
        Groupe groupe = (Groupe)  comgroupe.getSelectedItem();
        rqt.setLong("id_g", groupe.getIdG());
        List<Examen> ex=rqt.list();
        
        comexam.removeAllItems();
        for(Examen e: ex)
            comexam.addItem(e);
        comexam.addItemListener(ec);
    }//GEN-LAST:event_comgroupeItemStateChanged

   class EcouteurExamen implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent evt) {
            
          Query q= s.createQuery("from Notes n where n.examen.idEx =:id");
          Examen e = (Examen)  comexam.getSelectedItem();
          q.setLong("id", e.getIdEx());
          List<Notes> ln=q.list();
          DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
          df.setRowCount(0);
            System.out.println(ln.size());
          if(ln.size()>0){
              for(Notes n :ln)
                  df.addRow(new Object[]{n.getEtudiant().getIdE(),n.getEtudiant().getNom(),n.getEtudiant().getPrenom(),n.getNote()});
          }else
          {   
              //Transaction tx = s.beginTransaction();
              for(Etudiant et:e.getGroupe().getEtudiants()){
                        df.addRow(new Object[]{et.getIdE(),et.getNom(),et.getPrenom(),null});
                      //  Notes n= new Notes(new NotesId(e.getIdEx(), et.getIdE()),et,null);
                       // s.save(n);
              }
           //  tx.commit();
             //s.flush();
          }
        }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Examen> comexam;
    private javax.swing.JComboBox<Groupe> comgroupe;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
